# Site settings
title: PyLadies Brasil
email: brazil@pyladies.com
description: "We are an international mentorship group with a focus on helping more women become active participants and leaders in the pyhton open-source community."
baseurl: ""
url: "http://brazil.pyladies.com"
username: pyladies-brazil

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["Gemfile", "Gemfile.lock", "README.md", ".gitignore", "_deploy_brasil.sh"]
